# This file is machine-generated - editing it directly is not advised

julia_version = "1.9.2"
manifest_format = "2.0"
project_hash = "05e4ed7a5915e8369cad206dee460d46a1dc7bcb"

[[deps.IOCapture]]
deps = ["Logging", "Random"]
git-tree-sha1 = "3fc23ea5ba2f82e35df0bf9d4766968c13aa5e39"
pinned = true
repo-url = "https://github.com/musoke/IOCapture.jl"
uuid = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
version = "0.2.3"

[[deps.Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[deps.Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[deps.MathLink]]
deps = ["Libdl", "Printf"]
git-tree-sha1 = "e005449169d6154347d954f1a2eb6f3f8f001bba"
pinned = true
repo-url = "https://github.com/musoke/MathLink.jl"
uuid = "18c93696-a329-5786-9845-8443133fa0b4"
version = "0.5.1"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[deps.Random]]
deps = ["SHA", "Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
